import {
  User,
  VendorProfile,
  Category,
  City,
  Pincode,
  Product,
  Order,
  DeliveryPerson,
  Shipment,
  ReturnRequest,
  WithdrawalRequest,
  Coupon,
  Banner,
  HomepagePin,
  ProductReview,
  SupportTicket,
  IssueReport,
  CompetitiveExam,
  AppSetting,
  PushNotificationLog,
  AdminActionLog,
  EmailLog,
  MigrationLog,
} from './types';

export const mockUsers: User[] = [
  {
    id: 'u-101',
    wp_id: 101,
    phone: '+919876543210',
    email: 'rahul.kumar@gmail.com',
    display_name: 'Rahul Kumar',
    role: 'customer',
    wallet_balance: 450,
    is_active: true,
    is_banned: false,
    is_migrated: true,
    migration_login_done: true,
    last_login_at: '2026-08-01 14:20',
    created_at: '2025-03-12',
  },
  {
    id: 'u-102',
    wp_id: 102,
    phone: '+919812345678',
    email: 'priya.sharma@yahoo.com',
    display_name: 'Priya Sharma',
    role: 'customer',
    wallet_balance: 120,
    is_active: true,
    is_banned: false,
    is_migrated: true,
    migration_login_done: false,
    last_login_at: '2026-07-28 11:15',
    created_at: '2025-05-20',
  },
  {
    id: 'u-201',
    wp_id: 201,
    phone: '+919771122334',
    email: 'mitras.books@kitabwalah.com',
    display_name: 'Mitra Book Depot',
    role: 'vendor',
    wallet_balance: 0,
    is_active: true,
    is_banned: false,
    is_migrated: true,
    migration_login_done: true,
    last_login_at: '2026-08-01 16:45',
    created_at: '2024-11-05',
  },
  {
    id: 'u-202',
    wp_id: 202,
    phone: '+919430098765',
    email: 'bihar.publishers@gmail.com',
    display_name: 'Bihar Books Emporium',
    role: 'vendor',
    wallet_balance: 0,
    is_active: true,
    is_banned: false,
    is_migrated: true,
    migration_login_done: true,
    last_login_at: '2026-08-01 10:00',
    created_at: '2025-01-15',
  },
  {
    id: 'u-301',
    phone: '+919123456789',
    email: 'ramesh.delivery@kitabwalah.com',
    display_name: 'Ramesh Singh',
    role: 'delivery_person',
    wallet_balance: 0,
    is_active: true,
    is_banned: false,
    is_migrated: false,
    migration_login_done: false,
    last_login_at: '2026-08-01 17:30',
    created_at: '2025-06-01',
  },
];

export const mockVendors: VendorProfile[] = [
  {
    id: 'v-1',
    user_id: 'u-201',
    store_name: 'Mitra Book Depot (Muzaffarpur)',
    store_slug: 'mitra-book-depot',
    gstin: '10ABCDE1234F1Z5',
    commission_rate: 10,
    total_earnings: 145000,
    total_withdrawn: 120000,
    pending_balance: 25000,
    average_rating: 4.8,
    total_reviews: 124,
    is_verified: true,
    kyc_form_data: {
      pan_number: 'ABCDE1234F',
      aadhaar_last4: '9876',
      business_type: 'Proprietorship',
      address: 'Motijheel Road, Muzaffarpur, Bihar 842001',
      bank_account: '91802004561234',
      ifsc: 'SBIN0000137',
    },
    vacation_mode: false,
    is_active: true,
    user: mockUsers[2],
  },
  {
    id: 'v-2',
    user_id: 'u-202',
    store_name: 'Bihar Books & Stationers',
    store_slug: 'bihar-books',
    gstin: '10XYZPS9876K1Z9',
    commission_rate: 10,
    total_earnings: 89000,
    total_withdrawn: 75000,
    pending_balance: 14000,
    average_rating: 4.5,
    total_reviews: 68,
    is_verified: true,
    kyc_form_data: {
      pan_number: 'XYZPS9876K',
      aadhaar_last4: '4321',
      business_type: 'Partnership',
      address: 'Boring Road, Patna, Bihar 800001',
      bank_account: '001201509988',
      ifsc: 'HDFC0000240',
    },
    vacation_mode: false,
    is_active: true,
    user: mockUsers[3],
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    wp_id: 15,
    name: 'School & NCERT Books',
    slug: 'school-ncert-books',
    display_order: 1,
    is_active: true,
    subcategories: [
      { id: 'cat-11', name: 'Class 10 NCERT', slug: 'class-10-ncert', display_order: 1, is_active: true },
      { id: 'cat-12', name: 'Class 12 NCERT', slug: 'class-12-ncert', display_order: 2, is_active: true },
    ],
  },
  {
    id: 'cat-2',
    wp_id: 18,
    name: 'Competitive Exams',
    slug: 'competitive-exams',
    display_order: 2,
    is_active: true,
    subcategories: [
      { id: 'cat-21', name: 'UPSC Civil Services', slug: 'upsc', display_order: 1, is_active: true },
      { id: 'cat-22', name: 'SSC CGL & CHSL', slug: 'ssc', display_order: 2, is_active: true },
      { id: 'cat-23', name: 'NEET & JEE Main', slug: 'neet-jee', display_order: 3, is_active: true },
    ],
  },
  {
    id: 'cat-3',
    wp_id: 22,
    name: 'Stationery & Supplies',
    slug: 'stationery',
    display_order: 3,
    is_active: true,
  },
];

export const mockCities: City[] = [
  { id: 'city-1', name: 'Muzaffarpur', slug: 'muzaffarpur', is_active: true },
  { id: 'city-2', name: 'Patna', slug: 'patna', is_active: true },
  { id: 'city-3', name: 'Boring Road (Patna Hub)', slug: 'boring-road', is_active: true },
  { id: 'city-4', name: 'Gaya', slug: 'gaya', is_active: true },
  { id: 'city-5', name: 'Darbhanga', slug: 'darbhanga', is_active: true },
];

export const mockPincodes: Pincode[] = [
  {
    id: 'pin-842001',
    pincode: '842001',
    city_id: 'city-1',
    city_name: 'Muzaffarpur',
    delivery_zone: 'local',
    cod_type: 'full_cod',
    partial_cod_amount: 0,
    is_same_day_eligible: true,
    is_delivery_available: true,
  },
  {
    id: 'pin-842002',
    pincode: '842002',
    city_id: 'city-1',
    city_name: 'Muzaffarpur',
    delivery_zone: 'local',
    cod_type: 'full_cod',
    partial_cod_amount: 0,
    is_same_day_eligible: true,
    is_delivery_available: true,
  },
  {
    id: 'pin-800001',
    pincode: '800001',
    city_id: 'city-2',
    city_name: 'Patna',
    delivery_zone: 'rest_bihar',
    cod_type: 'partial_cod',
    partial_cod_amount: 50,
    is_same_day_eligible: false,
    is_delivery_available: true,
  },
  {
    id: 'pin-560001',
    pincode: '560001',
    city_id: 'city-6',
    city_name: 'Bengaluru',
    delivery_zone: 'south_india',
    cod_type: 'prepaid_only',
    partial_cod_amount: 0,
    is_same_day_eligible: false,
    is_delivery_available: true,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-101',
    wp_id: 4986,
    vendor_id: 'v-1',
    vendor_name: 'Mitra Book Depot',
    title: 'NCERT Mathematics Class 10th (English Medium)',
    slug: 'ncert-math-class-10',
    regular_price: 160,
    sale_price: 145,
    gst_rate: 0,
    hsn_code: '4901',
    sku: 'NCERT-M10-ENG',
    isbn: '9788174506344',
    author: 'NCERT Editorial Board',
    book_format: 'physical',
    condition: 'new_condition',
    stock_quantity: 42,
    status: 'active',
    category_name: 'School & NCERT Books',
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400'],
    city_prices: {
      'city-1': 140,
      'city-2': 145,
    },
  },
  {
    id: 'prod-102',
    wp_id: 4987,
    vendor_id: 'v-1',
    vendor_name: 'Mitra Book Depot',
    title: 'UPSC Civil Services General Studies Paper-1 Manual 2026',
    slug: 'upsc-gs-manual-2026',
    regular_price: 895,
    sale_price: 699,
    gst_rate: 0,
    hsn_code: '4901',
    sku: 'UPSC-GS1-2026',
    isbn: '9789354601123',
    author: 'McGraw Hill Editors',
    book_format: 'physical',
    condition: 'new_condition',
    stock_quantity: 18,
    status: 'active',
    category_name: 'Competitive Exams',
    images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400'],
  },
  {
    id: 'prod-103',
    wp_id: 4988,
    vendor_id: 'v-2',
    vendor_name: 'Bihar Books & Stationers',
    title: 'Classmate Octane Gel Pen Pack of 10 (Blue)',
    slug: 'classmate-octane-gel-blue-10',
    regular_price: 100,
    sale_price: 90,
    gst_rate: 18,
    hsn_code: '9608',
    sku: 'PEN-OCTANE-BL10',
    book_format: 'physical',
    condition: 'new_condition',
    stock_quantity: 3, // low stock alert!
    status: 'active',
    category_name: 'Stationery & Supplies',
    images: ['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=400'],
  },
  {
    id: 'prod-104',
    vendor_id: 'v-2',
    vendor_name: 'Bihar Books & Stationers',
    title: 'BPSC Combined Competitive Exam Solved Papers (2010-2025)',
    slug: 'bpsc-solved-papers',
    regular_price: 450,
    sale_price: 380,
    gst_rate: 0,
    hsn_code: '4901',
    sku: 'BPSC-SOLVED-25',
    author: 'Kiran Publication',
    book_format: 'physical',
    condition: 'new_condition',
    stock_quantity: 25,
    status: 'pending_review',
    category_name: 'Competitive Exams',
    images: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400'],
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'KW-2026-8812',
    user_id: 'u-101',
    customer_name: 'Rahul Kumar',
    customer_phone: '+919876543210',
    status: 'delivered',
    payment_status: 'paid',
    payment_method: 'razorpay',
    subtotal: 844,
    shipping_amount: 39,
    cod_charge: 0,
    discount_amount: 50,
    gst_amount: 16.2,
    total: 849.2,
    is_cod: false,
    delivery_type: 'same_day',
    pincode: '842001',
    city: 'Muzaffarpur',
    invoice_number: 'INV-2026-001001',
    razorpay_payment_id: 'pay_PQR123890XYZ',
    delivered_at: '2026-08-01 13:10',
    created_at: '2026-08-01 10:30',
    items: [
      {
        id: 'oi-1',
        order_id: 'ord-1001',
        product_id: 'prod-101',
        vendor_id: 'v-1',
        product_name: 'NCERT Mathematics Class 10th',
        unit_price: 145,
        quantity: 1,
        total_price: 145,
        gst_rate: 0,
        gst_amount: 0,
        status: 'active',
      },
      {
        id: 'oi-2',
        order_id: 'ord-1001',
        product_id: 'prod-102',
        vendor_id: 'v-1',
        product_name: 'UPSC Civil Services GS Manual 2026',
        unit_price: 699,
        quantity: 1,
        total_price: 699,
        gst_rate: 0,
        gst_amount: 0,
        status: 'active',
      },
    ],
    shipping_address: {
      order_id: 'ord-1001',
      address_type: 'shipping',
      first_name: 'Rahul',
      last_name: 'Kumar',
      address_1: 'Flat 302, Royal Residency, Motijheel',
      city: 'Muzaffarpur',
      state: 'Bihar',
      pincode: '842001',
      phone: '+919876543210',
    },
  },
  {
    id: 'ord-1002',
    order_number: 'KW-2026-8813',
    user_id: 'u-102',
    customer_name: 'Priya Sharma',
    customer_phone: '+919812345678',
    status: 'processing',
    payment_status: 'paid',
    payment_method: 'wallet',
    subtotal: 380,
    shipping_amount: 49,
    cod_charge: 0,
    discount_amount: 30,
    gst_amount: 0,
    total: 399,
    is_cod: false,
    delivery_type: 'normal',
    pincode: '800001',
    city: 'Patna',
    invoice_number: 'INV-2026-001002',
    created_at: '2026-08-01 15:45',
    items: [
      {
        id: 'oi-3',
        order_id: 'ord-1002',
        product_id: 'prod-104',
        vendor_id: 'v-2',
        product_name: 'BPSC Combined Competitive Exam Solved Papers',
        unit_price: 380,
        quantity: 1,
        total_price: 380,
        gst_rate: 0,
        gst_amount: 0,
        status: 'active',
      },
    ],
  },
];

export const mockDeliveryPersons: DeliveryPerson[] = [
  {
    id: 'dp-1',
    user_id: 'u-301',
    name: 'Ramesh Singh',
    phone: '+919123456789',
    vehicle_type: 'Hero Splendor (Bike)',
    vehicle_number: 'BR 06 AB 4321',
    last_location_lat: 26.1209,
    last_location_lng: 85.3647,
    is_available: true,
    is_active: true,
    salary_per_month: 16000,
    current_assigned_orders: 1,
  },
  {
    id: 'dp-2',
    user_id: 'u-302',
    name: 'Sunil Kumar',
    phone: '+919835011223',
    vehicle_type: 'TVS Jupiter (Scooter)',
    vehicle_number: 'BR 06 CD 8765',
    last_location_lat: 26.1285,
    last_location_lng: 85.3812,
    is_available: true,
    is_active: true,
    salary_per_month: 16000,
    current_assigned_orders: 0,
  },
];

export const mockShipments: Shipment[] = [
  {
    id: 'shp-1',
    order_id: 'ord-1001',
    order_number: 'KW-2026-8812',
    delivery_person_id: 'dp-1',
    delivery_person_name: 'Ramesh Singh',
    delivery_type: 'same_day',
    status: 'delivered',
    tracking_id: 'KW-SD-8812-OTP',
    delivery_otp: '4892',
    actual_delivered_at: '2026-08-01 13:10',
    delivery_photo_url: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=300',
    delivery_attempts: 1,
    destination_city: 'Muzaffarpur',
  },
  {
    id: 'shp-2',
    order_id: 'ord-1002',
    order_number: 'KW-2026-8813',
    delivery_type: 'normal',
    status: 'in_transit',
    tracking_id: 'SFX99281044',
    shadowfax_order_id: 'SFX-PAT-0091',
    estimated_delivery_date: '2026-08-03',
    delivery_attempts: 0,
    destination_city: 'Patna',
  },
];

export const mockReturnRequests: ReturnRequest[] = [
  {
    id: 'ret-1',
    order_id: 'ord-994',
    order_number: 'KW-2026-8790',
    order_item_id: 'oi-99',
    product_name: 'NCERT Chemistry Class 12th',
    user_id: 'u-101',
    user_name: 'Rahul Kumar',
    reason: 'wrong_item',
    reason_description: 'Received Biology book instead of Chemistry.',
    proof_images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300'],
    status: 'pending',
    refund_amount: 195,
    created_at: '2026-08-01 09:15',
  },
];

export const mockWithdrawalRequests: WithdrawalRequest[] = [
  {
    id: 'w-1',
    wp_id: 501,
    vendor_id: 'v-1',
    vendor_name: 'Mitra Book Depot',
    store_name: 'Mitra Book Depot (Muzaffarpur)',
    amount: 15000,
    status: 'pending',
    requested_at: '2026-08-01 08:30',
    bank_details: {
      account_number: '91802004561234',
      ifsc: 'SBIN0000137',
      upi_id: 'mitrabooks@sbi',
    },
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: 'c-1',
    code: 'KITABWALAH',
    type: 'percentage',
    value: 10,
    used_count: 1420,
    is_birthday_coupon: false,
    is_first_order_only: false,
    valid_from: '2026-01-01',
    valid_until: '2026-12-31',
    is_active: true,
  },
  {
    id: 'c-2',
    code: 'NEW10',
    type: 'percentage',
    value: 10,
    min_order_amount: 199,
    used_count: 850,
    is_birthday_coupon: false,
    is_first_order_only: true,
    valid_from: '2026-01-01',
    valid_until: '2026-12-31',
    is_active: true,
  },
  {
    id: 'c-3',
    code: 'BIRTHDAY10',
    type: 'percentage',
    value: 10,
    max_discount_amount: 50,
    used_count: 94,
    is_birthday_coupon: true,
    is_first_order_only: false,
    valid_from: '2026-01-01',
    valid_until: '2026-12-31',
    is_active: true,
  },
  {
    id: 'c-4',
    code: 'WELCOME30',
    type: 'fixed_amount',
    value: 30,
    min_order_amount: 299,
    used_count: 610,
    is_birthday_coupon: false,
    is_first_order_only: true,
    valid_from: '2026-01-01',
    valid_until: '2026-12-31',
    is_active: true,
  },
];

export const mockBanners: Banner[] = [
  {
    id: 'b-1',
    title: 'Monsoon Exam Preparation Sale',
    subtitle: 'Flat 20% off on all UPSC & BPSC Study Material',
    image_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
    action_type: 'category',
    action_value: 'cat-2',
    display_order: 1,
    valid_from: '2026-07-01',
    valid_until: '2026-08-31',
    is_active: true,
  },
  {
    id: 'b-2',
    title: 'Same-Day Book Delivery in Muzaffarpur',
    subtitle: 'Order before 2 PM, get delivered by 7 PM',
    image_url: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800',
    action_type: 'none',
    display_order: 2,
    valid_from: '2026-01-01',
    valid_until: '2026-12-31',
    is_active: true,
  },
];

export const mockHomepagePins: HomepagePin[] = [
  {
    id: 'pin-1',
    type: 'product',
    reference_id: 'prod-101',
    title: 'NCERT Mathematics Class 10th',
    position: 1,
    is_active: true,
    updated_at: '2026-07-30',
  },
  {
    id: 'pin-2',
    type: 'category',
    reference_id: 'cat-2',
    title: 'Competitive Exams Spotlight',
    position: 2,
    is_active: true,
    updated_at: '2026-07-28',
  },
];

export const mockReviews: ProductReview[] = [
  {
    id: 'rev-1',
    product_id: 'prod-101',
    product_name: 'NCERT Mathematics Class 10th',
    user_id: 'u-101',
    user_name: 'Rahul Kumar',
    vendor_id: 'v-1',
    vendor_name: 'Mitra Book Depot',
    rating: 5,
    title: 'Original book in crisp condition!',
    content: 'Delivered within 3 hours in Muzaffarpur. 100% original NCERT edition.',
    is_verified_purchase: true,
    status: 'approved',
    created_at: '2026-08-01 14:00',
  },
  {
    id: 'rev-2',
    product_id: 'prod-102',
    product_name: 'UPSC Civil Services GS Manual 2026',
    user_id: 'u-102',
    user_name: 'Priya Sharma',
    vendor_id: 'v-1',
    vendor_name: 'Mitra Book Depot',
    rating: 4,
    title: 'Very useful for GS Paper 1',
    content: 'Thoroughly revised edition with mock papers. Good packaging.',
    is_verified_purchase: true,
    status: 'pending',
    created_at: '2026-08-01 16:10',
  },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'st-1',
    user_id: 'u-102',
    user_name: 'Priya Sharma',
    user_role: 'customer',
    order_id: 'ord-1002',
    subject: 'Inquiry regarding Patna delivery date',
    message: 'When can I expect the BPSC solved papers delivered to Boring Road Patna?',
    status: 'open',
    created_at: '2026-08-01 16:00',
  },
];

export const mockIssueReports: IssueReport[] = [
  {
    id: 'ir-1',
    user_id: 'u-101',
    user_name: 'Rahul Kumar',
    order_id: 'ord-1001',
    category: 'payment',
    description: 'Wallet top-up showed processing for 2 mins before success on Razorpay.',
    status: 'resolved',
    resolution_note: 'Verified Razorpay webhook payload. Transaction settled smoothly.',
    created_at: '2026-07-31 18:20',
  },
];

export const mockCompetitiveExams: CompetitiveExam[] = [
  {
    id: 'exam-1',
    name: 'UPSC Civil Services (IAS/IPS)',
    slug: 'upsc-civil-services',
    description: 'Complete study material, NCERT compilations & standard reference books',
    image_url: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=500',
    display_order: 1,
    is_active: true,
    linked_products_count: 86,
  },
  {
    id: 'exam-2',
    name: 'BPSC (Bihar Public Service Commission)',
    slug: 'bpsc-exam',
    description: 'BPSC Prelims, Mains, Bihar Special GK & Previous Year Solved Papers',
    image_url: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=500',
    display_order: 2,
    is_active: true,
    linked_products_count: 64,
  },
  {
    id: 'exam-3',
    name: 'SSC CGL & CHSL',
    slug: 'ssc-cgl-chsl',
    description: 'Quantitative Aptitude, Reasoning, English & General Awareness',
    image_url: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500',
    display_order: 3,
    is_active: true,
    linked_products_count: 112,
  },
];

export const mockAppSettings: AppSetting[] = [
  { id: 's-1', key: 'delivery_charge_local', value: '39', description: 'Local Zone delivery charge (17 Muzaffarpur pincodes)', updated_at: '2026-07-18' },
  { id: 's-2', key: 'delivery_charge_bihar', value: '49', description: 'Rest of Bihar delivery charge', updated_at: '2026-07-18' },
  { id: 's-3', key: 'delivery_charge_south', value: '59', description: 'South India zone delivery charge', updated_at: '2026-07-18' },
  { id: 's-4', key: 'delivery_charge_rest', value: '59', description: 'Rest of India delivery charge', updated_at: '2026-07-18' },
  { id: 's-5', key: 'free_delivery_local', value: '500', description: 'Order amount for free local delivery', updated_at: '2026-07-18' },
  { id: 's-6', key: 'free_delivery_bihar', value: '599', description: 'Order amount for free Bihar delivery', updated_at: '2026-07-18' },
  { id: 's-7', key: 'cod_charge', value: '7', description: 'Flat COD charge per order', updated_at: '2026-07-18' },
  { id: 's-8', key: 'default_commission_rate', value: '10', description: 'Default platform commission % for vendors', updated_at: '2026-07-18' },
  { id: 's-9', key: 'gst_stationery', value: '18', description: 'GST rate for stationery items', updated_at: '2026-07-18' },
  { id: 's-10', key: 'gst_shipping', value: '18', description: 'GST rate for shipping charges', updated_at: '2026-07-18' },
  { id: 's-11', key: 'reseller_commission', value: '25', description: 'Wallet credit awarded to referrer on first order', updated_at: '2026-07-18' },
  { id: 's-12', key: 'razorpay_key_id', value: 'rzp_live_KW992810398', description: 'Razorpay Payment Gateway Key ID', updated_at: '2026-07-18' },
];

export const mockPushNotifications: PushNotificationLog[] = [
  {
    id: 'pn-1',
    target_group: 'all',
    title: '📚 Monsoon Book Sale is LIVE!',
    body: 'Get up to 25% off on NCERT & UPSC exam books. Order today!',
    data_payload: '{"screen": "category", "id": "cat-2"}',
    sent_count: 14200,
    sent_at: '2026-08-01 11:00',
  },
];

export const mockAdminActionLogs: AdminActionLog[] = [
  {
    id: 'log-1',
    admin_id: 'admin-001',
    admin_name: 'Super Admin',
    action_type: 'product_approve',
    target_table: 'products',
    target_id: 'prod-101',
    description: 'Approved NCERT Mathematics Class 10th listing by Mitra Book Depot.',
    created_at: '2026-08-01 10:15',
  },
  {
    id: 'log-2',
    admin_id: 'admin-001',
    admin_name: 'Super Admin',
    action_type: 'pincode_update',
    target_table: 'pincodes',
    target_id: 'pin-842001',
    description: 'Set same-day delivery status to ENABLED for pincode 842001.',
    created_at: '2026-07-31 14:00',
  },
];

export const mockEmailLogs: EmailLog[] = [
  {
    id: 'em-1',
    to_email: 'rahul.kumar@gmail.com',
    subject: 'Order #KW-2026-8812 Delivered Successfully!',
    message: 'Your order consisting of NCERT Math & UPSC Manual has been delivered by Ramesh Singh.',
    status: 'sent',
    sent_at: '2026-08-01 13:10',
  },
  {
    id: 'em-2',
    to_email: 'mitras.books@kitabwalah.com',
    subject: 'New Order Received #KW-2026-8812',
    message: 'Please pack 2 items for same-day delivery pickup.',
    status: 'sent',
    sent_at: '2026-08-01 10:31',
  },
];

export const mockMigrationLogs: MigrationLog[] = [
  {
    id: 'mig-1',
    source_db: 'u101172427_newdev (WordPress + WooCommerce + WCFM)',
    source_table: 'wp_posts (product)',
    destination_table: 'products',
    records_migrated: 4986,
    records_failed: 0,
    records_skipped: 0,
    status: 'completed',
    started_at: '2026-07-18 10:00',
    completed_at: '2026-07-18 10:04',
  },
  {
    id: 'mig-2',
    source_db: 'u101172427_newdev (WordPress + WooCommerce + WCFM)',
    source_table: 'wp_wc_orders',
    destination_table: 'orders',
    records_migrated: 1001,
    records_failed: 0,
    records_skipped: 680, // guest orders skipped as per spec
    status: 'completed',
    started_at: '2026-07-18 10:05',
    completed_at: '2026-07-18 10:07',
  },
  {
    id: 'mig-3',
    source_db: 'u101172427_newdev (WordPress + WooCommerce + WCFM)',
    source_table: 'wp_users',
    destination_table: 'users',
    records_migrated: 938,
    records_failed: 0,
    records_skipped: 0,
    status: 'completed',
    started_at: '2026-07-18 10:08',
    completed_at: '2026-07-18 10:10',
  },
];
